name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash --noprofile --norc -e -o pipefail -o igncr {0}
    env:
      PATH: C:\cygwin\bin
    steps:
      - name: Install Cygwin Git and cygport
        uses: cygwin/cygwin-install-action@v2
        with:
          packages: git cygport
        timeout-minutes: 10
      - name: Manually configure safe.directory
        run: git config --global --add safe.directory '*'
        timeout-minutes: 1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: false  # actions/checkout otherwise tries to use the wrong config file, per actions/checkout#767
          fetch-depth: 0  # Need this to push to Cygwin Git mirror
        timeout-minutes: 1
      - name: Generate cygcheck output
        if: always()
        run: cygcheck -srv >/var/log/cygcheck.out
        timeout-minutes: 5
      - name: Store Cygwin logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cygwin-logs
          path: 'C:\cygwin\var\log\'
        timeout-minutes: 5
      - name: Load variables from the cygport file
        run: |
          eval "$(cygport luajit-lpeg.cygport vars BUILD_REQUIRES PVR)"
          printf 'BUILD_REQUIRES=%s\n' "$BUILD_REQUIRES" >>"$GITHUB_ENV"
          printf 'PVR=%s\n' "$PVR" >>"$GITHUB_ENV"
      - name: Install build requirements
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: ${{ env.BUILD_REQUIRES }}
          site: |
            https://cygwin.paktolos.net
            http://mirrors.kernel.org/sourceware/cygwin/
          pubkeys: https://kgraefe.paktolos.net/AA73A441.bin
        timeout-minutes: 30
      - name: Cygport download
        run: cygport luajit-lpeg.cygport download
        timeout-minutes: 5
      - name: Cygport prep
        run: cygport luajit-lpeg.cygport prep
        timeout-minutes: 1
      - name: Cygport compile
        run: cygport luajit-lpeg.cygport compile
        timeout-minutes: 30
      - name: Cygport test
        run: cygport luajit-lpeg.cygport test
        timeout-minutes: 300
      - name: Cygport install
        run: cygport luajit-lpeg.cygport install
        timeout-minutes: 30
      - name: Cygport package
        run: cygport luajit-lpeg.cygport package
        timeout-minutes: 5
      - name: Tar up build results
        if: always()
        run: tar -caf luajit-lpeg-build-results.txz luajit-lpeg-*-*.*/
        timeout-minutes: 10
      - name: Store build results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-results
          path: luajit-lpeg-build-results.txz
          if-no-files-found: error
        timeout-minutes: 5
      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            luajit-lpeg-${{ env.PVR }}.x86_64/dist/luajit-lpeg/luajit-lpeg-${{ env.PVR }}.tar.xz
            luajit-lpeg-${{ env.PVR }}.x86_64/dist/luajit-lpeg/luajit-lpeg-${{ env.PVR }}-src.tar.xz
            luajit-lpeg-${{ env.PVR }}.x86_64/dist/luajit-lpeg/luajit-lpeg-debuginfo/luajit-lpeg-debuginfo-${{ env.PVR }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
